name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v -race

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 $TAG^ 2>/dev/null || echo "")
          
          # Generate release notes
          if [ -z "$PREV_TAG" ]; then
            NOTES="## Initial Release $TAG\n\n$(git log --pretty=format:"- %s (%h)" $TAG)"
          else
            NOTES="## Changes since $PREV_TAG\n\n$(git log --pretty=format:"- %s (%h)" $PREV_TAG..$TAG)"
          fi
          
          # Create the release
          gh release create $TAG \
            --title "$TAG" \
            --notes "$NOTES" 